### ISSUE TITLE
DIV renders at top of page, irregardless of page scrolling

### ISSUE THREAD

**Issue by msf004** [nj-coder/nj-timepicker#3]
First, awesome time picker!

My time entry is located well below the fold on my page.  Meaning, you must scroll down to get to the container for the nj-picker.  However, when the container is clicked, the pop occurs at the top of the page (absolute positioning?).  The user must then scroll up to get to the time picker.

To Reproduce
1. You can use the downloadable demo to simply add a bunch of content to the top of the page.  Ensuring the nj-picker container is accessible by scrolling down.
2. click on the nj-picker container to pop the nj-picker.
3. you can see that you must scroll up to access the nj-picker.

I believe all that is needed is to change the .nj-picker position from absolute to "fixed", but I could be mistaken or oversimplifying.

**Comment by nj-coder** [comment]
This issue is fixed in [v1.2.102](https://github.com/nj-coder/nj-timepicker/blob/master/Changelog.md) (https://github.com/nj-coder/nj-timepicker/commit/81de097)
