### ISSUE TITLE
Fill a input field

### ISSUE THREAD

**Issue by gitFrank** [nj-coder/nj-timepicker#4]
I can use your timepicker for a div and it works. If try to use instead a input field it happens nothing.
Is using input field possible?

**Comment by nj-coder** [comment]
@gitFrank for now, you need to use the save event to get the data and set your input box. But, i think this is a good feature to have especially with input boxes. I will add this in the coming days, Thanks

**Comment by gitFrank** [comment]
Hello, this would be great. I could need it for a pizza order page for preorders. Your timepicker is the nicest i've seen. Thanks and *thumb up*

**Comment by nj-coder** [comment]
@gitFrank this is included in the commit 0d00cdd. Please feel free to use the latest version from the [dist/](https://github.com/nj-coder/nj-timepicker/tree/master/dist). I'll release with other backlog items in the coming days.
