### ISSUE TITLE
For multilingual

### ISSUE THREAD

**Issue by gitFrank** [nj-coder/nj-timepicker#5]
Hi, you changes for input field works like a charme. Thank you.

Now i want change some words: Hours, Minutes, Save, Clear, Close.
But only headerText is easy changable. 
Save, Clear, Close is middle heavy changable.
Hours and Minutes i can't change. 
Would be nice if it is all so easy changeable like headerText. :-)

Other point: your min-width of 350px is too big for my old iPhone 5, have to reduce it to 320px

**Comment by nj-coder** [comment]
@gitFrank  The above issues/enhancements are included in this commit 4409f99. 
You can use the [texts config](https://github.com/nj-coder/nj-timepicker#configuration) to change the texts for the picker. As far as phone sizes are concerned, I have provided a CSS variable `--picker-min-width` which you can change using media queries to support iPhone 5. Please find the updated configs for this under [theming section](https://github.com/nj-coder/nj-timepicker#theming).

I will have a release soon, but if this is a blocker, please find the latest code in [dist folder](https://github.com/nj-coder/nj-timepicker/tree/master/dist)
