### ISSUE TITLE
Initiate Timepicker with default hours or minutes

### ISSUE THREAD

**Issue by DienH** [nj-coder/nj-timepicker#6]
I think it would be great if we could initiate the timepicker with a default hour or minutes that is already selected when the picker is triggered.

The configuration could be like this :

```
var picker = new NJTimePicker({
      ...
      defaultHour : "12",
      defaultMinutes: "30",
      ...
})
```

**Comment by nj-coder** [comment]
yep, agree. Will do, thanks

**Comment by nj-coder** [comment]
@DienH this can be achieved using the `setValue()` after the `ready` event

 ```
format_12_picker.on('ready', function (data) {
        format_12_picker.setValue({
            hours: 12,
            minutes: 45,
            ampm: 'am'
        });
});
```
