### ISSUE TITLE
After changing button text, ie: close: 'Cerrar', buttons become non-functional.

### ISSUE THREAD

**Issue by mabaro13** [nj-coder/nj-timepicker#8]
**Describe the bug**
According to configuration options, the text of the buttons can be changed.
{
header: ''
hours: 'Hours'
minutes: 'Minutes'
ampm: 'AM/PM'
save: 'Save'
clear: 'Clear'
close: 'Close'
}

However, setting the new text for save and/or clear and/or close (save: 'Guardar') is doing such buttons become non-functional.

**To Reproduce**
Steps to reproduce the behaviour:
1. Change settings: texts: { header: 'Inicia',
		                            hours: 'Hora',
		                            minutes: 'Minutos',
		                            ampm: 'am/pm',
		                            save: 'Guardar'      //*************************************
		                        }
2. Save changes and load html page which display nj-timepicker.
4. Click the element which fires nj-timepicker and select a time.
5. Click 'Guardar' or 'Clear' or 'Close' button. 
6. Any button does not function.

**Expected behaviour**
Button keep working as if not change of text were applied.

**Additional context**
[Clock.zip](https://github.com/nj-coder/nj-timepicker/files/4574725/Clock.zip)

**Comment by nj-coder** [comment]
This issue is fixed in v1.3.118 ([571724b](https://github.com/nj-coder/nj-timepicker/commit/571724b))
